export const TEAM_NAMES_PTBR: Record<string, string> = {
  "Brazil": "Brasil",
  "Morocco": "Marrocos",
  "Haiti": "Haiti",
  "Scotland": "Escócia",
  "Panama": "Panamá",
  "Panama national football team": "Panamá",
  "Egypt": "Egito",
  "Egypt national football team": "Egito",
  "Argentina": "Argentina",
  "France": "França",
  "Germany": "Alemanha",
  "Spain": "Espanha",
  "Portugal": "Portugal",
  "England": "Inglaterra",
  "Netherlands": "Holanda",
  "Belgium": "Bélgica",
  "Croatia": "Croácia",
  "Uruguay": "Uruguai",
  "Colombia": "Colômbia",
  "Mexico": "México",
  "Japan": "Japão",
  "South Korea": "Coreia do Sul",
  "Senegal": "Senegal",
  "Nigeria": "Nigéria",
  "Australia": "Austrália",
  "Switzerland": "Suíça",
  "Denmark": "Dinamarca",
  "United States": "Estados Unidos",
  "USA": "EUA",
  "Canada": "Canadá",
  "Ecuador": "Equador",
  "Peru": "Peru",
  "Chile": "Chile",
  "Venezuela": "Venezuela",
  "Bolivia": "Bolívia",
  "Paraguay": "Paraguai",
  "South Africa": "África do Sul",
  "Tunisia": "Tunísia",
  "Algeria": "Argélia",
  "Ghana": "Gana",
  "DR Congo": "R.D. Congo",
  "Cabo Verde": "Cabo Verde",
  "Qatar": "Catar",
  "Saudi Arabia": "Arábia Saudita",
  "Iraq": "Iraque",
  "Iran": "Irã",
  "Jordan": "Jordânia",
  "Türkiye": "Turquia",
  "Austria": "Áustria",
  "Norway": "Noruega",
  "Sweden": "Suécia",
  "Czech Republic": "Rep. Tcheca",
  "Czechia": "Rep. Tcheca",
  "Bosnia & Herzegovina": "Bósnia",
  "New Zealand": "Nova Zelândia",
  "Uzbekistan": "Uzbequistão",
  "Côte d'Ivoire": "Costa do Marfim",
  "Curaçao": "Curaçao",
  "A definir": "A definir",
};

// Mapeamento: nome do time (em inglês) → ID Sofascore
export const TEAM_FLAG_ID: Record<string, number> = {
  "Mexico": 4781,
  "South Africa": 4736,
  "South Korea": 4735,
  "Czechia": 4714,
  "Czech Republic": 4714,
  "Canada": 4752,
  "Bosnia & Herzegovina": 4479,
  "Qatar": 4792,
  "Switzerland": 4699,
  "Brazil": 4748,
  "Morocco": 4778,
  "Haiti": 7229,
  "Scotland": 4695,
  "USA": 4724,
  "United States": 4724,
  "Paraguay": 4789,
  "Australia": 4741,
  "Türkiye": 4700,
  "Germany": 4711,
  "Curaçao": 55827,
  "Côte d'Ivoire": 4768,
  "Ecuador": 4757,
  "Netherlands": 4705,
  "Japan": 4770,
  "Sweden": 4688,
  "Tunisia": 4729,
  "Belgium": 4717,
  "Egypt": 4758,
  "Iran": 4766,
  "New Zealand": 4784,
  "Spain": 4698,
  "Cabo Verde": 4753,
  "Saudi Arabia": 4834,
  "Uruguay": 4725,
  "France": 4481,
  "Senegal": 4739,
  "Iraq": 4767,
  "Norway": 4475,
  "Argentina": 4819,
  "Algeria": 4691,
  "Austria": 4718,
  "Jordan": 4771,
  "Portugal": 4704,
  "DR Congo": 4823,
  "Uzbekistan": 4723,
  "Colombia": 4820,
  "England": 4713,
  "Croatia": 4715,
  "Ghana": 4764,
  "Panama": 5164,
  "Egypt national football team": 4758,
  "Panama national football team": 5164,
};

// Mapeamento PT → ID Sofascore (48 times Copa 2026)
const TEAM_FLAG_ID_PT: Record<string, number> = {
  "África do Sul":       4736,
  "Alemanha":            4711,
  "Arábia Saudita":      4834,
  "Argélia":             4691,
  "Argentina":           4819,
  "Austrália":           4741,
  "Áustria":             4718,
  "Bélgica":             4717,
  "Bósnia e Herzegovina":4479,
  "Brasil":              4748,
  "Cabo Verde":          4753,
  "Canadá":              4752,
  "Catar":               4792,
  "Colômbia":            4820,
  "Coreia do Sul":       4735,
  "Costa do Marfim":     4768,
  "Croácia":             4715,
  "Curaçao":             55827,
  "Egito":               4758,
  "Equador":             4757,
  "Escócia":             4695,
  "Espanha":             4698,
  "Estados Unidos":      4724,
  "França":              4481,
  "Gana":                4764,
  "Haiti":               7229,
  "Holanda":             4705,
  "Inglaterra":          4713,
  "Irã":                 4766,
  "Iraque":              4767,
  "Japão":               4770,
  "Jordânia":            4771,
  "Marrocos":            4778,
  "México":              4781,
  "Nova Zelândia":       4784,
  "Noruega":             4475,
  "Panamá":              5164,
  "Paraguai":            4789,
  "Portugal":            4704,
  "R.D. Congo":          4823,
  "Rep. Tcheca":         4714,
  "Senegal":             4739,
  "Suécia":              4688,
  "Suíça":               4699,
  "Tunísia":             4729,
  "Turquia":             4700,
  "Uruguai":             4725,
  "Uzbequistão":         4723,
  // aliases
  "Qatar":               4792,
  "Bósnia":              4479,
};

export function teamName(name: string): string {
  if (!name) return name;
  return TEAM_NAMES_PTBR[name] ?? name;
}

/** Retorna a URL da bandeira via proxy para um nome de time (em inglês) */
export function teamFlagUrl(name: string): string | null {
  const id = TEAM_FLAG_ID[name];
  if (!id) return null;
  return `/api/flag/${id}`;
}

/** Retorna a URL da bandeira para um nome de time (em português ou inglês) */
export function teamFlagUrlByName(name: string): string | null {
  const id = TEAM_FLAG_ID_PT[name] ?? TEAM_FLAG_ID[name];
  if (!id) return null;
  return `/api/flag/${id}`;
}
